### ISSUE TITLE
 User Story 1: Set up basic Express application.

### ISSUE THREAD

**Issue by Lambric42** [SchoolOfCode/bc17-w4d2-project-three-musketeers#1]
Given I am a new developer joining the team,
When I clone down the backend repo,
Then I should see a clear README that details how to install and run the application using Node through a command line. The application is an Express API.

Given I am a developer who has just followed the instructions to run and install the application (our Express APP),
When I make a GET request to “http://localhost:3000/”,
Then I should get back a response with status code of 200 and text saying “Hello World!”
Then I should also see that the Node API has also logged the request in the terminal (console.log)

```[tasklist]
### Tasks
- [x] npm init
- [x] install express
- [x] create main server file
- [x] In index.js: Import and initialize express module and port 3000
- [x] In index.js: Declare app.get with res.status(200) and Message "Hello World"
- [x] In index.js: Declare app.listen with console.log message "Hello World"
- [x] Add instructions to README - copy from express install/prev workshops
```
