### ISSUE TITLE
User Story 2: Add basic security standards using Helmet 

### ISSUE THREAD

**Issue by Lambric42** [SchoolOfCode/bc17-w4d2-project-three-musketeers#2]
Given I am a developer who clones down the Activity API repo,
When I look at the top level app file,
Then I should see Helmet configured as one of the first pieces of middleware.

Given I am a developer who makes a request to the Activity API,
When I inspect the response headers,
Then I should not be able to see the response header “X-Powered-By: Express”.
```[tasklist]
### Tasks
- [x] install helmet in npm
- [x] In index.js: import helmet
- [x] In index.js: Create middleware using helmet
```
