### ISSUE TITLE
User Story 4: Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by ikefika** [SchoolOfCode/bc17-w4d2-project-three-musketeers#4]
Description:

As Kenny, a busy front end engineer I need to be able to send a POST request with a JSON request body (new activity) to the API so that I can make a simple form that allows my user to submit new activity.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a POST request to “http://localhost:3000/activities” with a request body containing a JSON object (new activity),
Then the API should save the new activity to the activities.json file giving it a unique “id” (UUID) and activity_submitted (time stamp - Date.now()),
Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body (response.data).
````
// request object - new user activity
{
    "activity_type": "run",
    "activity_duration": "30",
}
​
// save the newly sumbitted activity in activities.JSON 
​
[
    {}, // exisitng activity
    {}, // exisitng activity
    {
        "id": "54321234", // Add a UUID
        "date": "1719486190058", // Add the date time stamp
        "activity_type": "run",
        "activity_duration": "30",
    }
]
````
Given I am a developer who has made an invalid POST request by missing a required request body field like, activity_type or activity_duration,
When I inspect the API response,
Then the request should fail, responding with the correct status code and a clear error message (response.error).
```[tasklist]
### Tasks
- [x] write basic post request to submit .json body
- [x] download the UUID module
- [x] add new UUID to post request obj - calls a function in UUID module to create a new ID in json.body
- [x] timestamp use built in date.now
- [x] use spread to combine id, timestamp and req.body into one variable
- [x] use push to add the new activity onto the end of the activities array.
- [x] error handling to check if valid keys in req.body - activity_type and activity_duration
- [x] Error handling to check if values of keys in req.body were string for activity_type and number for activity_duration
```
